language: cpp c
before_install:
#openSSL 1.0.2 stable
- wget -O openssl.zip -c https://github.com/openssl/openssl/archive/OpenSSL_1_0_2-stable.zip
- unzip openssl.zip
- cd openssl-OpenSSL_1_0_2-stable
- ./config --prefix=/usr/local
- make
- sudo make install
- cd ..
compiler: 
- gcc
- clang

# Change this to your needs
script:  cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo && make
