language: cpp
sudo: required
dist: trusty
before_install:
- sudo apt-get install -y libjson-c-dev
#openSSL 1.0.2 stable
- wget -O openssl.zip -c https://github.com/openssl/openssl/archive/OpenSSL_1_0_2-stable.zip
- unzip openssl.zip
- cd openssl-OpenSSL_1_0_2-stable
- ./config --prefix=/usr/local -fPIC
- make
- sudo make install
- cd ..
compiler:
  - clang
  - gcc
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=RelWithDebInfo

# Change this to your needs
script:  cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make
